// Generated by gencpp from file barc/ECU.msg
// DO NOT EDIT!


#ifndef BARC_MESSAGE_ECU_H
#define BARC_MESSAGE_ECU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace barc
{
template <class ContainerAllocator>
struct ECU_
{
  typedef ECU_<ContainerAllocator> Type;

  ECU_()
    : motor(0.0)
    , servo(0.0)  {
    }
  ECU_(const ContainerAllocator& _alloc)
    : motor(0.0)
    , servo(0.0)  {
  (void)_alloc;
    }



   typedef float _motor_type;
  _motor_type motor;

   typedef float _servo_type;
  _servo_type servo;




  typedef boost::shared_ptr< ::barc::ECU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::barc::ECU_<ContainerAllocator> const> ConstPtr;

}; // struct ECU_

typedef ::barc::ECU_<std::allocator<void> > ECU;

typedef boost::shared_ptr< ::barc::ECU > ECUPtr;
typedef boost::shared_ptr< ::barc::ECU const> ECUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::barc::ECU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::barc::ECU_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace barc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'barc': ['/home/odroid/barc/workspace/src/barc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::barc::ECU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::barc::ECU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::ECU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::ECU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::ECU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::ECU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::barc::ECU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e60fd3690167c0df782fc50cceb5ce82";
  }

  static const char* value(const ::barc::ECU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe60fd3690167c0dfULL;
  static const uint64_t static_value2 = 0x782fc50cceb5ce82ULL;
};

template<class ContainerAllocator>
struct DataType< ::barc::ECU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "barc/ECU";
  }

  static const char* value(const ::barc::ECU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::barc::ECU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message to hold data for the ECU (electronic control unit)\n\
#\n\
# Units may vary depending on the topic\n\
# The motor controls the speeds of the vehicle through an input torque. (For input force, divide by radius of tire) \n\
# The servo controls the steering angle\n\
#\n\
# For modeling and state estimation, motors units are [N], and servo units are [rad]\n\
# For actuator signals, both have units of PWM angle [deg]. This relates to the duty cycle\n\
float32 motor \n\
float32 servo\n\
";
  }

  static const char* value(const ::barc::ECU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::barc::ECU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor);
      stream.next(m.servo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ECU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::barc::ECU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::barc::ECU_<ContainerAllocator>& v)
  {
    s << indent << "motor: ";
    Printer<float>::stream(s, indent + "  ", v.motor);
    s << indent << "servo: ";
    Printer<float>::stream(s, indent + "  ", v.servo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BARC_MESSAGE_ECU_H
