// Generated by gencpp from file barc/Encoder.msg
// DO NOT EDIT!


#ifndef BARC_MESSAGE_ENCODER_H
#define BARC_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace barc
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : FL(0.0)
    , FR(0.0)
    , BL(0.0)
    , BR(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : FL(0.0)
    , FR(0.0)
    , BL(0.0)
    , BR(0.0)  {
  (void)_alloc;
    }



   typedef float _FL_type;
  _FL_type FL;

   typedef float _FR_type;
  _FR_type FR;

   typedef float _BL_type;
  _BL_type BL;

   typedef float _BR_type;
  _BR_type BR;




  typedef boost::shared_ptr< ::barc::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::barc::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::barc::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::barc::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::barc::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::barc::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::barc::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace barc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'barc': ['/home/odroid/barc/workspace/src/barc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::barc::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::barc::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::barc::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32ae9320a3544d34b8e4e844525161ab";
  }

  static const char* value(const ::barc::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32ae9320a3544d34ULL;
  static const uint64_t static_value2 = 0xb8e4e844525161abULL;
};

template<class ContainerAllocator>
struct DataType< ::barc::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "barc/Encoder";
  }

  static const char* value(const ::barc::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::barc::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 FL \n\
float32 FR\n\
float32 BL\n\
float32 BR\n\
";
  }

  static const char* value(const ::barc::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::barc::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FL);
      stream.next(m.FR);
      stream.next(m.BL);
      stream.next(m.BR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::barc::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::barc::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "FL: ";
    Printer<float>::stream(s, indent + "  ", v.FL);
    s << indent << "FR: ";
    Printer<float>::stream(s, indent + "  ", v.FR);
    s << indent << "BL: ";
    Printer<float>::stream(s, indent + "  ", v.BL);
    s << indent << "BR: ";
    Printer<float>::stream(s, indent + "  ", v.BR);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BARC_MESSAGE_ENCODER_H
