// Generated by gencpp from file barc/Ultrasound.msg
// DO NOT EDIT!


#ifndef BARC_MESSAGE_ULTRASOUND_H
#define BARC_MESSAGE_ULTRASOUND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace barc
{
template <class ContainerAllocator>
struct Ultrasound_
{
  typedef Ultrasound_<ContainerAllocator> Type;

  Ultrasound_()
    : front(0.0)
    , back(0.0)
    , right(0.0)
    , left(0.0)  {
    }
  Ultrasound_(const ContainerAllocator& _alloc)
    : front(0.0)
    , back(0.0)
    , right(0.0)
    , left(0.0)  {
  (void)_alloc;
    }



   typedef float _front_type;
  _front_type front;

   typedef float _back_type;
  _back_type back;

   typedef float _right_type;
  _right_type right;

   typedef float _left_type;
  _left_type left;




  typedef boost::shared_ptr< ::barc::Ultrasound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::barc::Ultrasound_<ContainerAllocator> const> ConstPtr;

}; // struct Ultrasound_

typedef ::barc::Ultrasound_<std::allocator<void> > Ultrasound;

typedef boost::shared_ptr< ::barc::Ultrasound > UltrasoundPtr;
typedef boost::shared_ptr< ::barc::Ultrasound const> UltrasoundConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::barc::Ultrasound_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::barc::Ultrasound_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace barc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'barc': ['/home/odroid/barc/workspace/src/barc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::barc::Ultrasound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::barc::Ultrasound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::Ultrasound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::Ultrasound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::Ultrasound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::Ultrasound_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::barc::Ultrasound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a28144c3266e5b701faa1e4761aa50f9";
  }

  static const char* value(const ::barc::Ultrasound_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa28144c3266e5b70ULL;
  static const uint64_t static_value2 = 0x1faa1e4761aa50f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::barc::Ultrasound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "barc/Ultrasound";
  }

  static const char* value(const ::barc::Ultrasound_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::barc::Ultrasound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 front\n\
float32 back\n\
float32 right\n\
float32 left\n\
";
  }

  static const char* value(const ::barc::Ultrasound_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::barc::Ultrasound_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
      stream.next(m.back);
      stream.next(m.right);
      stream.next(m.left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ultrasound_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::barc::Ultrasound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::barc::Ultrasound_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<float>::stream(s, indent + "  ", v.front);
    s << indent << "back: ";
    Printer<float>::stream(s, indent + "  ", v.back);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BARC_MESSAGE_ULTRASOUND_H
