// Generated by gencpp from file barc/Z_KinBkMdl.msg
// DO NOT EDIT!


#ifndef BARC_MESSAGE_Z_KINBKMDL_H
#define BARC_MESSAGE_Z_KINBKMDL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace barc
{
template <class ContainerAllocator>
struct Z_KinBkMdl_
{
  typedef Z_KinBkMdl_<ContainerAllocator> Type;

  Z_KinBkMdl_()
    : x(0.0)
    , y(0.0)
    , psi(0.0)
    , v(0.0)  {
    }
  Z_KinBkMdl_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , psi(0.0)
    , v(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _psi_type;
  _psi_type psi;

   typedef float _v_type;
  _v_type v;




  typedef boost::shared_ptr< ::barc::Z_KinBkMdl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::barc::Z_KinBkMdl_<ContainerAllocator> const> ConstPtr;

}; // struct Z_KinBkMdl_

typedef ::barc::Z_KinBkMdl_<std::allocator<void> > Z_KinBkMdl;

typedef boost::shared_ptr< ::barc::Z_KinBkMdl > Z_KinBkMdlPtr;
typedef boost::shared_ptr< ::barc::Z_KinBkMdl const> Z_KinBkMdlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::barc::Z_KinBkMdl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::barc::Z_KinBkMdl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace barc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'barc': ['/home/odroid/barc/workspace/src/barc/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::barc::Z_KinBkMdl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::barc::Z_KinBkMdl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::Z_KinBkMdl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::barc::Z_KinBkMdl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::Z_KinBkMdl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::barc::Z_KinBkMdl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::barc::Z_KinBkMdl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c719f8bc9903c4ed5c145b22b3badcc";
  }

  static const char* value(const ::barc::Z_KinBkMdl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c719f8bc9903c4eULL;
  static const uint64_t static_value2 = 0xd5c145b22b3badccULL;
};

template<class ContainerAllocator>
struct DataType< ::barc::Z_KinBkMdl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "barc/Z_KinBkMdl";
  }

  static const char* value(const ::barc::Z_KinBkMdl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::barc::Z_KinBkMdl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 psi\n\
float32 v\n\
";
  }

  static const char* value(const ::barc::Z_KinBkMdl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::barc::Z_KinBkMdl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.psi);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Z_KinBkMdl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::barc::Z_KinBkMdl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::barc::Z_KinBkMdl_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "psi: ";
    Printer<float>::stream(s, indent + "  ", v.psi);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BARC_MESSAGE_Z_KINBKMDL_H
