#!/bin/bash


source=1
if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
    source=0
fi

source_exit() {
    if [ ${source} -eq 1 ]; then
        exit ${1}
    fi
}

error_handle() { 
    echo "Invalid syntax. Use 'rosbarc_network -h' for help on usage" >&2
    source_exit 1
}

if [ $# -lt 1 ]; then
    error_handle
fi

case $1 in

    "-m" )
        source ./sshcar -s
        master=$(rosparam get master 2> /dev/null)
        echo "$master"
        if [ -n "${master}" ]; then
            echo "According to the parameter server, a master already exists.
            If you would like to make this car the master, either
            stop the current master and restart the network with this car, or
            take this car off the current network and make it a master on a new network." >&2
            source_exit 1
        else
            roslaunch network_testing mastercar.launch car:=$(hostname) & 
        fi
    ;;

    "-s" )
        if [ $# -eq 2 ]; then
            ./sshcar -l ${2}
        elif [$# -eq 1 ]; then
            roslaunch network_testing slavecar.launch car:=$(hostname) &
        else
            error_handle
        fi
        
    ;;

    "-h" )
        echo "Manual:
            source rosbarc_network [FLAG] [ARG]
        "
    ;;

    * )
        error_handle
    ;;

esac

source_exit 0
