#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from barc_gui.gui import MyGUI

plugin = 'barc_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))#, plugin_argument_provider=Dot.add_arguments))
