// Generated by gencpp from file data_service/DataForward.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_DATAFORWARD_H
#define DATA_SERVICE_MESSAGE_DATAFORWARD_H

#include <ros/service_traits.h>


#include <data_service/DataForwardRequest.h>
#include <data_service/DataForwardResponse.h>


namespace data_service
{

struct DataForward
{

typedef DataForwardRequest Request;
typedef DataForwardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DataForward
} // namespace data_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_service::DataForward > {
  static const char* value()
  {
    return "f8d627aa29376505cccbe1058f0ed9d2";
  }

  static const char* value(const ::data_service::DataForward&) { return value(); }
};

template<>
struct DataType< ::data_service::DataForward > {
  static const char* value()
  {
    return "data_service/DataForward";
  }

  static const char* value(const ::data_service::DataForward&) { return value(); }
};


// service_traits::MD5Sum< ::data_service::DataForwardRequest> should match 
// service_traits::MD5Sum< ::data_service::DataForward > 
template<>
struct MD5Sum< ::data_service::DataForwardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::DataForward >::value();
  }
  static const char* value(const ::data_service::DataForwardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::DataForwardRequest> should match 
// service_traits::DataType< ::data_service::DataForward > 
template<>
struct DataType< ::data_service::DataForwardRequest>
{
  static const char* value()
  {
    return DataType< ::data_service::DataForward >::value();
  }
  static const char* value(const ::data_service::DataForwardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_service::DataForwardResponse> should match 
// service_traits::MD5Sum< ::data_service::DataForward > 
template<>
struct MD5Sum< ::data_service::DataForwardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::DataForward >::value();
  }
  static const char* value(const ::data_service::DataForwardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::DataForwardResponse> should match 
// service_traits::DataType< ::data_service::DataForward > 
template<>
struct DataType< ::data_service::DataForwardResponse>
{
  static const char* value()
  {
    return DataType< ::data_service::DataForward >::value();
  }
  static const char* value(const ::data_service::DataForwardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_DATAFORWARD_H
