// Generated by gencpp from file data_service/DataRetrieve.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_DATARETRIEVE_H
#define DATA_SERVICE_MESSAGE_DATARETRIEVE_H

#include <ros/service_traits.h>


#include <data_service/DataRetrieveRequest.h>
#include <data_service/DataRetrieveResponse.h>


namespace data_service
{

struct DataRetrieve
{

typedef DataRetrieveRequest Request;
typedef DataRetrieveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DataRetrieve
} // namespace data_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_service::DataRetrieve > {
  static const char* value()
  {
    return "f58abbeb8edc41005a341386540c1d0b";
  }

  static const char* value(const ::data_service::DataRetrieve&) { return value(); }
};

template<>
struct DataType< ::data_service::DataRetrieve > {
  static const char* value()
  {
    return "data_service/DataRetrieve";
  }

  static const char* value(const ::data_service::DataRetrieve&) { return value(); }
};


// service_traits::MD5Sum< ::data_service::DataRetrieveRequest> should match 
// service_traits::MD5Sum< ::data_service::DataRetrieve > 
template<>
struct MD5Sum< ::data_service::DataRetrieveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::DataRetrieve >::value();
  }
  static const char* value(const ::data_service::DataRetrieveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::DataRetrieveRequest> should match 
// service_traits::DataType< ::data_service::DataRetrieve > 
template<>
struct DataType< ::data_service::DataRetrieveRequest>
{
  static const char* value()
  {
    return DataType< ::data_service::DataRetrieve >::value();
  }
  static const char* value(const ::data_service::DataRetrieveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_service::DataRetrieveResponse> should match 
// service_traits::MD5Sum< ::data_service::DataRetrieve > 
template<>
struct MD5Sum< ::data_service::DataRetrieveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::DataRetrieve >::value();
  }
  static const char* value(const ::data_service::DataRetrieveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::DataRetrieveResponse> should match 
// service_traits::DataType< ::data_service::DataRetrieve > 
template<>
struct DataType< ::data_service::DataRetrieveResponse>
{
  static const char* value()
  {
    return DataType< ::data_service::DataRetrieve >::value();
  }
  static const char* value(const ::data_service::DataRetrieveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_DATARETRIEVE_H
