// Generated by gencpp from file data_service/DataRetrieveRequest.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_DATARETRIEVEREQUEST_H
#define DATA_SERVICE_MESSAGE_DATARETRIEVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_service
{
template <class ContainerAllocator>
struct DataRetrieveRequest_
{
  typedef DataRetrieveRequest_<ContainerAllocator> Type;

  DataRetrieveRequest_()
    : id()
    , is_time(false)  {
    }
  DataRetrieveRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , is_time(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef uint8_t _is_time_type;
  _is_time_type is_time;




  typedef boost::shared_ptr< ::data_service::DataRetrieveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_service::DataRetrieveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DataRetrieveRequest_

typedef ::data_service::DataRetrieveRequest_<std::allocator<void> > DataRetrieveRequest;

typedef boost::shared_ptr< ::data_service::DataRetrieveRequest > DataRetrieveRequestPtr;
typedef boost::shared_ptr< ::data_service::DataRetrieveRequest const> DataRetrieveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_service::DataRetrieveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_service::DataRetrieveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'data_service': ['/home/odroid/barc/workspace/src/data_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_service::DataRetrieveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::DataRetrieveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::DataRetrieveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75d582623a3182fcdab95d52c5168aba";
  }

  static const char* value(const ::data_service::DataRetrieveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75d582623a3182fcULL;
  static const uint64_t static_value2 = 0xdab95d52c5168abaULL;
};

template<class ContainerAllocator>
struct DataType< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_service/DataRetrieveRequest";
  }

  static const char* value(const ::data_service::DataRetrieveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n\
bool is_time\n\
";
  }

  static const char* value(const ::data_service::DataRetrieveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.is_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataRetrieveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_service::DataRetrieveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_service::DataRetrieveRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "is_time: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_DATARETRIEVEREQUEST_H
