// Generated by gencpp from file data_service/DataRetrieveResponse.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_DATARETRIEVERESPONSE_H
#define DATA_SERVICE_MESSAGE_DATARETRIEVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <data_service/CustomSignal.h>

namespace data_service
{
template <class ContainerAllocator>
struct DataRetrieveResponse_
{
  typedef DataRetrieveResponse_<ContainerAllocator> Type;

  DataRetrieveResponse_()
    : signal()  {
    }
  DataRetrieveResponse_(const ContainerAllocator& _alloc)
    : signal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::data_service::CustomSignal_<ContainerAllocator>  _signal_type;
  _signal_type signal;




  typedef boost::shared_ptr< ::data_service::DataRetrieveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_service::DataRetrieveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DataRetrieveResponse_

typedef ::data_service::DataRetrieveResponse_<std::allocator<void> > DataRetrieveResponse;

typedef boost::shared_ptr< ::data_service::DataRetrieveResponse > DataRetrieveResponsePtr;
typedef boost::shared_ptr< ::data_service::DataRetrieveResponse const> DataRetrieveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_service::DataRetrieveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_service::DataRetrieveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'data_service': ['/home/odroid/barc/workspace/src/data_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_service::DataRetrieveResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::DataRetrieveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::DataRetrieveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed8e16fd675a2c47988d9dbfca608537";
  }

  static const char* value(const ::data_service::DataRetrieveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed8e16fd675a2c47ULL;
  static const uint64_t static_value2 = 0x988d9dbfca608537ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_service/DataRetrieveResponse";
  }

  static const char* value(const ::data_service::DataRetrieveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CustomSignal signal\n\
\n\
================================================================================\n\
MSG: data_service/CustomSignal\n\
string id\n\
string signal\n\
";
  }

  static const char* value(const ::data_service::DataRetrieveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataRetrieveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_service::DataRetrieveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_service::DataRetrieveResponse_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    s << std::endl;
    Printer< ::data_service::CustomSignal_<ContainerAllocator> >::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_DATARETRIEVERESPONSE_H
