// Generated by gencpp from file data_service/RegisterVideoRequest.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_REGISTERVIDEOREQUEST_H
#define DATA_SERVICE_MESSAGE_REGISTERVIDEOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_service
{
template <class ContainerAllocator>
struct RegisterVideoRequest_
{
  typedef RegisterVideoRequest_<ContainerAllocator> Type;

  RegisterVideoRequest_()
    : experiment()
    , path()  {
    }
  RegisterVideoRequest_(const ContainerAllocator& _alloc)
    : experiment(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _experiment_type;
  _experiment_type experiment;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;




  typedef boost::shared_ptr< ::data_service::RegisterVideoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_service::RegisterVideoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterVideoRequest_

typedef ::data_service::RegisterVideoRequest_<std::allocator<void> > RegisterVideoRequest;

typedef boost::shared_ptr< ::data_service::RegisterVideoRequest > RegisterVideoRequestPtr;
typedef boost::shared_ptr< ::data_service::RegisterVideoRequest const> RegisterVideoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_service::RegisterVideoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_service::RegisterVideoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'data_service': ['/home/odroid/barc/workspace/src/data_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_service::RegisterVideoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::RegisterVideoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::RegisterVideoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baad6537a8fac26f3bc46b1b86efbaac";
  }

  static const char* value(const ::data_service::RegisterVideoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaad6537a8fac26fULL;
  static const uint64_t static_value2 = 0x3bc46b1b86efbaacULL;
};

template<class ContainerAllocator>
struct DataType< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_service/RegisterVideoRequest";
  }

  static const char* value(const ::data_service::RegisterVideoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string experiment\n\
string path\n\
";
  }

  static const char* value(const ::data_service::RegisterVideoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.experiment);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterVideoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_service::RegisterVideoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_service::RegisterVideoRequest_<ContainerAllocator>& v)
  {
    s << indent << "experiment: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.experiment);
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_REGISTERVIDEOREQUEST_H
