// Generated by gencpp from file data_service/RegisterExperimentRequest.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_REGISTEREXPERIMENTREQUEST_H
#define DATA_SERVICE_MESSAGE_REGISTEREXPERIMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_service
{
template <class ContainerAllocator>
struct RegisterExperimentRequest_
{
  typedef RegisterExperimentRequest_<ContainerAllocator> Type;

  RegisterExperimentRequest_()
    : experiment()  {
    }
  RegisterExperimentRequest_(const ContainerAllocator& _alloc)
    : experiment(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _experiment_type;
  _experiment_type experiment;




  typedef boost::shared_ptr< ::data_service::RegisterExperimentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_service::RegisterExperimentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterExperimentRequest_

typedef ::data_service::RegisterExperimentRequest_<std::allocator<void> > RegisterExperimentRequest;

typedef boost::shared_ptr< ::data_service::RegisterExperimentRequest > RegisterExperimentRequestPtr;
typedef boost::shared_ptr< ::data_service::RegisterExperimentRequest const> RegisterExperimentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_service::RegisterExperimentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'data_service': ['/home/odroid/barc/workspace/src/data_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_service::RegisterExperimentRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::RegisterExperimentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::RegisterExperimentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5af7b7e6b332ce1133c33bfeadc80af";
  }

  static const char* value(const ::data_service::RegisterExperimentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5af7b7e6b332ce1ULL;
  static const uint64_t static_value2 = 0x133c33bfeadc80afULL;
};

template<class ContainerAllocator>
struct DataType< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_service/RegisterExperimentRequest";
  }

  static const char* value(const ::data_service::RegisterExperimentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string experiment\n\
";
  }

  static const char* value(const ::data_service::RegisterExperimentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.experiment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterExperimentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_service::RegisterExperimentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_service::RegisterExperimentRequest_<ContainerAllocator>& v)
  {
    s << indent << "experiment: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.experiment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_REGISTEREXPERIMENTREQUEST_H
