// Generated by gencpp from file data_service/RegisterExperiment.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_REGISTEREXPERIMENT_H
#define DATA_SERVICE_MESSAGE_REGISTEREXPERIMENT_H

#include <ros/service_traits.h>


#include <data_service/RegisterExperimentRequest.h>
#include <data_service/RegisterExperimentResponse.h>


namespace data_service
{

struct RegisterExperiment
{

typedef RegisterExperimentRequest Request;
typedef RegisterExperimentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterExperiment
} // namespace data_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_service::RegisterExperiment > {
  static const char* value()
  {
    return "23efeb8a860ffcd264ebd586a8c57078";
  }

  static const char* value(const ::data_service::RegisterExperiment&) { return value(); }
};

template<>
struct DataType< ::data_service::RegisterExperiment > {
  static const char* value()
  {
    return "data_service/RegisterExperiment";
  }

  static const char* value(const ::data_service::RegisterExperiment&) { return value(); }
};


// service_traits::MD5Sum< ::data_service::RegisterExperimentRequest> should match 
// service_traits::MD5Sum< ::data_service::RegisterExperiment > 
template<>
struct MD5Sum< ::data_service::RegisterExperimentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::RegisterExperiment >::value();
  }
  static const char* value(const ::data_service::RegisterExperimentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::RegisterExperimentRequest> should match 
// service_traits::DataType< ::data_service::RegisterExperiment > 
template<>
struct DataType< ::data_service::RegisterExperimentRequest>
{
  static const char* value()
  {
    return DataType< ::data_service::RegisterExperiment >::value();
  }
  static const char* value(const ::data_service::RegisterExperimentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_service::RegisterExperimentResponse> should match 
// service_traits::MD5Sum< ::data_service::RegisterExperiment > 
template<>
struct MD5Sum< ::data_service::RegisterExperimentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::RegisterExperiment >::value();
  }
  static const char* value(const ::data_service::RegisterExperimentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::RegisterExperimentResponse> should match 
// service_traits::DataType< ::data_service::RegisterExperiment > 
template<>
struct DataType< ::data_service::RegisterExperimentResponse>
{
  static const char* value()
  {
    return DataType< ::data_service::RegisterExperiment >::value();
  }
  static const char* value(const ::data_service::RegisterExperimentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_REGISTEREXPERIMENT_H
