// Generated by gencpp from file data_service/RegisterVideo.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_REGISTERVIDEO_H
#define DATA_SERVICE_MESSAGE_REGISTERVIDEO_H

#include <ros/service_traits.h>


#include <data_service/RegisterVideoRequest.h>
#include <data_service/RegisterVideoResponse.h>


namespace data_service
{

struct RegisterVideo
{

typedef RegisterVideoRequest Request;
typedef RegisterVideoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterVideo
} // namespace data_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_service::RegisterVideo > {
  static const char* value()
  {
    return "252bc0f1ff2ebd98b97d212fe2c3fb57";
  }

  static const char* value(const ::data_service::RegisterVideo&) { return value(); }
};

template<>
struct DataType< ::data_service::RegisterVideo > {
  static const char* value()
  {
    return "data_service/RegisterVideo";
  }

  static const char* value(const ::data_service::RegisterVideo&) { return value(); }
};


// service_traits::MD5Sum< ::data_service::RegisterVideoRequest> should match 
// service_traits::MD5Sum< ::data_service::RegisterVideo > 
template<>
struct MD5Sum< ::data_service::RegisterVideoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::RegisterVideo >::value();
  }
  static const char* value(const ::data_service::RegisterVideoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::RegisterVideoRequest> should match 
// service_traits::DataType< ::data_service::RegisterVideo > 
template<>
struct DataType< ::data_service::RegisterVideoRequest>
{
  static const char* value()
  {
    return DataType< ::data_service::RegisterVideo >::value();
  }
  static const char* value(const ::data_service::RegisterVideoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_service::RegisterVideoResponse> should match 
// service_traits::MD5Sum< ::data_service::RegisterVideo > 
template<>
struct MD5Sum< ::data_service::RegisterVideoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::RegisterVideo >::value();
  }
  static const char* value(const ::data_service::RegisterVideoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::RegisterVideoResponse> should match 
// service_traits::DataType< ::data_service::RegisterVideo > 
template<>
struct DataType< ::data_service::RegisterVideoResponse>
{
  static const char* value()
  {
    return DataType< ::data_service::RegisterVideo >::value();
  }
  static const char* value(const ::data_service::RegisterVideoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_REGISTERVIDEO_H
