// Generated by gencpp from file data_service/RegisterSetting.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_REGISTERSETTING_H
#define DATA_SERVICE_MESSAGE_REGISTERSETTING_H

#include <ros/service_traits.h>


#include <data_service/RegisterSettingRequest.h>
#include <data_service/RegisterSettingResponse.h>


namespace data_service
{

struct RegisterSetting
{

typedef RegisterSettingRequest Request;
typedef RegisterSettingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterSetting
} // namespace data_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::data_service::RegisterSetting > {
  static const char* value()
  {
    return "c268a698e75a634c50aaf2d35ec4caf2";
  }

  static const char* value(const ::data_service::RegisterSetting&) { return value(); }
};

template<>
struct DataType< ::data_service::RegisterSetting > {
  static const char* value()
  {
    return "data_service/RegisterSetting";
  }

  static const char* value(const ::data_service::RegisterSetting&) { return value(); }
};


// service_traits::MD5Sum< ::data_service::RegisterSettingRequest> should match 
// service_traits::MD5Sum< ::data_service::RegisterSetting > 
template<>
struct MD5Sum< ::data_service::RegisterSettingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::RegisterSetting >::value();
  }
  static const char* value(const ::data_service::RegisterSettingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::RegisterSettingRequest> should match 
// service_traits::DataType< ::data_service::RegisterSetting > 
template<>
struct DataType< ::data_service::RegisterSettingRequest>
{
  static const char* value()
  {
    return DataType< ::data_service::RegisterSetting >::value();
  }
  static const char* value(const ::data_service::RegisterSettingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::data_service::RegisterSettingResponse> should match 
// service_traits::MD5Sum< ::data_service::RegisterSetting > 
template<>
struct MD5Sum< ::data_service::RegisterSettingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::data_service::RegisterSetting >::value();
  }
  static const char* value(const ::data_service::RegisterSettingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::data_service::RegisterSettingResponse> should match 
// service_traits::DataType< ::data_service::RegisterSetting > 
template<>
struct DataType< ::data_service::RegisterSettingResponse>
{
  static const char* value()
  {
    return DataType< ::data_service::RegisterSetting >::value();
  }
  static const char* value(const ::data_service::RegisterSettingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_REGISTERSETTING_H
