// Generated by gencpp from file data_service/RegisterExperimentResponse.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_REGISTEREXPERIMENTRESPONSE_H
#define DATA_SERVICE_MESSAGE_REGISTEREXPERIMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_service
{
template <class ContainerAllocator>
struct RegisterExperimentResponse_
{
  typedef RegisterExperimentResponse_<ContainerAllocator> Type;

  RegisterExperimentResponse_()
    : experiment_id(0)  {
    }
  RegisterExperimentResponse_(const ContainerAllocator& _alloc)
    : experiment_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _experiment_id_type;
  _experiment_id_type experiment_id;




  typedef boost::shared_ptr< ::data_service::RegisterExperimentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_service::RegisterExperimentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterExperimentResponse_

typedef ::data_service::RegisterExperimentResponse_<std::allocator<void> > RegisterExperimentResponse;

typedef boost::shared_ptr< ::data_service::RegisterExperimentResponse > RegisterExperimentResponsePtr;
typedef boost::shared_ptr< ::data_service::RegisterExperimentResponse const> RegisterExperimentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_service::RegisterExperimentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'data_service': ['/home/odroid/barc/workspace/src/data_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_service::RegisterExperimentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::RegisterExperimentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::RegisterExperimentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bc044b3b8998aa44c7343356570fb87";
  }

  static const char* value(const ::data_service::RegisterExperimentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bc044b3b8998aa4ULL;
  static const uint64_t static_value2 = 0x4c7343356570fb87ULL;
};

template<class ContainerAllocator>
struct DataType< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_service/RegisterExperimentResponse";
  }

  static const char* value(const ::data_service::RegisterExperimentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 experiment_id\n\
";
  }

  static const char* value(const ::data_service::RegisterExperimentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.experiment_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterExperimentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_service::RegisterExperimentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_service::RegisterExperimentResponse_<ContainerAllocator>& v)
  {
    s << indent << "experiment_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.experiment_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_REGISTEREXPERIMENTRESPONSE_H
