// Generated by gencpp from file data_service/TimeSignal.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_TIMESIGNAL_H
#define DATA_SERVICE_MESSAGE_TIMESIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_service
{
template <class ContainerAllocator>
struct TimeSignal_
{
  typedef TimeSignal_<ContainerAllocator> Type;

  TimeSignal_()
    : name()
    , timestamps()
    , signal()  {
    }
  TimeSignal_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , timestamps(_alloc)
    , signal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _timestamps_type;
  _timestamps_type timestamps;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _signal_type;
  _signal_type signal;




  typedef boost::shared_ptr< ::data_service::TimeSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_service::TimeSignal_<ContainerAllocator> const> ConstPtr;

}; // struct TimeSignal_

typedef ::data_service::TimeSignal_<std::allocator<void> > TimeSignal;

typedef boost::shared_ptr< ::data_service::TimeSignal > TimeSignalPtr;
typedef boost::shared_ptr< ::data_service::TimeSignal const> TimeSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_service::TimeSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_service::TimeSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'data_service': ['/home/odroid/barc/workspace/src/data_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_service::TimeSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_service::TimeSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::TimeSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::TimeSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::TimeSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::TimeSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_service::TimeSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "242915a951390ccd66bdffda0979a29d";
  }

  static const char* value(const ::data_service::TimeSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x242915a951390ccdULL;
  static const uint64_t static_value2 = 0x66bdffda0979a29dULL;
};

template<class ContainerAllocator>
struct DataType< ::data_service::TimeSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_service/TimeSignal";
  }

  static const char* value(const ::data_service::TimeSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_service::TimeSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float64[] timestamps\n\
string signal\n\
";
  }

  static const char* value(const ::data_service::TimeSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_service::TimeSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.timestamps);
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_service::TimeSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_service::TimeSignal_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "timestamps[]" << std::endl;
    for (size_t i = 0; i < v.timestamps.size(); ++i)
    {
      s << indent << "  timestamps[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.timestamps[i]);
    }
    s << indent << "signal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_TIMESIGNAL_H
