// Generated by gencpp from file data_service/TimeData.msg
// DO NOT EDIT!


#ifndef DATA_SERVICE_MESSAGE_TIMEDATA_H
#define DATA_SERVICE_MESSAGE_TIMEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace data_service
{
template <class ContainerAllocator>
struct TimeData_
{
  typedef TimeData_<ContainerAllocator> Type;

  TimeData_()
    : timestamp(0.0)
    , value()  {
    }
  TimeData_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::data_service::TimeData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_service::TimeData_<ContainerAllocator> const> ConstPtr;

}; // struct TimeData_

typedef ::data_service::TimeData_<std::allocator<void> > TimeData;

typedef boost::shared_ptr< ::data_service::TimeData > TimeDataPtr;
typedef boost::shared_ptr< ::data_service::TimeData const> TimeDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_service::TimeData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_service::TimeData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'data_service': ['/home/odroid/barc/workspace/src/data_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_service::TimeData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_service::TimeData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::TimeData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_service::TimeData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::TimeData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_service::TimeData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_service::TimeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "806316970232f83725326f09cc93bc8a";
  }

  static const char* value(const ::data_service::TimeData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x806316970232f837ULL;
  static const uint64_t static_value2 = 0x25326f09cc93bc8aULL;
};

template<class ContainerAllocator>
struct DataType< ::data_service::TimeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_service/TimeData";
  }

  static const char* value(const ::data_service::TimeData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_service::TimeData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 timestamp\n\
float64[] value\n\
";
  }

  static const char* value(const ::data_service::TimeData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_service::TimeData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_service::TimeData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_service::TimeData_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_SERVICE_MESSAGE_TIMEDATA_H
