#!/usr/bin/env python

import sys

from rqt_bag.bag import Bag
from rqt_gui.main import Main

plugin = 'rqt_bag.bag.Bag'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Bag.add_arguments))
