// Generated by gencpp from file labs/Z_DynBkMdl.msg
// DO NOT EDIT!


#ifndef LABS_MESSAGE_Z_DYNBKMDL_H
#define LABS_MESSAGE_Z_DYNBKMDL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace labs
{
template <class ContainerAllocator>
struct Z_DynBkMdl_
{
  typedef Z_DynBkMdl_<ContainerAllocator> Type;

  Z_DynBkMdl_()
    : x(0.0)
    , y(0.0)
    , psi(0.0)
    , v_x(0.0)
    , v_y(0.0)
    , psi_dot(0.0)  {
    }
  Z_DynBkMdl_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , psi(0.0)
    , v_x(0.0)
    , v_y(0.0)
    , psi_dot(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _psi_type;
  _psi_type psi;

   typedef float _v_x_type;
  _v_x_type v_x;

   typedef float _v_y_type;
  _v_y_type v_y;

   typedef float _psi_dot_type;
  _psi_dot_type psi_dot;




  typedef boost::shared_ptr< ::labs::Z_DynBkMdl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::labs::Z_DynBkMdl_<ContainerAllocator> const> ConstPtr;

}; // struct Z_DynBkMdl_

typedef ::labs::Z_DynBkMdl_<std::allocator<void> > Z_DynBkMdl;

typedef boost::shared_ptr< ::labs::Z_DynBkMdl > Z_DynBkMdlPtr;
typedef boost::shared_ptr< ::labs::Z_DynBkMdl const> Z_DynBkMdlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::labs::Z_DynBkMdl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::labs::Z_DynBkMdl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace labs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'labs': ['/home/odroid/barc/workspace/src/labs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::labs::Z_DynBkMdl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::labs::Z_DynBkMdl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::labs::Z_DynBkMdl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::labs::Z_DynBkMdl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::labs::Z_DynBkMdl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::labs::Z_DynBkMdl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::labs::Z_DynBkMdl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fe12764dcdf3a7f6277d8c56c0c723c";
  }

  static const char* value(const ::labs::Z_DynBkMdl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fe12764dcdf3a7fULL;
  static const uint64_t static_value2 = 0x6277d8c56c0c723cULL;
};

template<class ContainerAllocator>
struct DataType< ::labs::Z_DynBkMdl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "labs/Z_DynBkMdl";
  }

  static const char* value(const ::labs::Z_DynBkMdl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::labs::Z_DynBkMdl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 psi\n\
float32 v_x\n\
float32 v_y\n\
float32 psi_dot\n\
";
  }

  static const char* value(const ::labs::Z_DynBkMdl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::labs::Z_DynBkMdl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.psi);
      stream.next(m.v_x);
      stream.next(m.v_y);
      stream.next(m.psi_dot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Z_DynBkMdl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::labs::Z_DynBkMdl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::labs::Z_DynBkMdl_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "psi: ";
    Printer<float>::stream(s, indent + "  ", v.psi);
    s << indent << "v_x: ";
    Printer<float>::stream(s, indent + "  ", v.v_x);
    s << indent << "v_y: ";
    Printer<float>::stream(s, indent + "  ", v.v_y);
    s << indent << "psi_dot: ";
    Printer<float>::stream(s, indent + "  ", v.psi_dot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LABS_MESSAGE_Z_DYNBKMDL_H
