// Generated by gencpp from file marvelmind_nav/hedge_pos.msg
// DO NOT EDIT!


#ifndef MARVELMIND_NAV_MESSAGE_HEDGE_POS_H
#define MARVELMIND_NAV_MESSAGE_HEDGE_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace marvelmind_nav
{
template <class ContainerAllocator>
struct hedge_pos_
{
  typedef hedge_pos_<ContainerAllocator> Type;

  hedge_pos_()
    : header()
    , timestamp_ms(0)
    , x_m(0.0)
    , y_m(0.0)
    , z_m(0.0)
    , flags(0)  {
    }
  hedge_pos_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp_ms(0)
    , x_m(0.0)
    , y_m(0.0)
    , z_m(0.0)
    , flags(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _timestamp_ms_type;
  _timestamp_ms_type timestamp_ms;

   typedef double _x_m_type;
  _x_m_type x_m;

   typedef double _y_m_type;
  _y_m_type y_m;

   typedef double _z_m_type;
  _z_m_type z_m;

   typedef uint8_t _flags_type;
  _flags_type flags;




  typedef boost::shared_ptr< ::marvelmind_nav::hedge_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marvelmind_nav::hedge_pos_<ContainerAllocator> const> ConstPtr;

}; // struct hedge_pos_

typedef ::marvelmind_nav::hedge_pos_<std::allocator<void> > hedge_pos;

typedef boost::shared_ptr< ::marvelmind_nav::hedge_pos > hedge_posPtr;
typedef boost::shared_ptr< ::marvelmind_nav::hedge_pos const> hedge_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marvelmind_nav::hedge_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace marvelmind_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'marvelmind_nav': ['/home/heyin/barc/workspace/src/ros_marvelmind_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marvelmind_nav::hedge_pos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marvelmind_nav::hedge_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvelmind_nav::hedge_pos_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29d7a738a044fe2e89bd305ae8fa5f2b";
  }

  static const char* value(const ::marvelmind_nav::hedge_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29d7a738a044fe2eULL;
  static const uint64_t static_value2 = 0x89bd305ae8fa5f2bULL;
};

template<class ContainerAllocator>
struct DataType< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marvelmind_nav/hedge_pos";
  }

  static const char* value(const ::marvelmind_nav::hedge_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int64 timestamp_ms\n\
float64 x_m\n\
float64 y_m\n\
float64 z_m\n\
uint8 flags\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::marvelmind_nav::hedge_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp_ms);
      stream.next(m.x_m);
      stream.next(m.y_m);
      stream.next(m.z_m);
      stream.next(m.flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hedge_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marvelmind_nav::hedge_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marvelmind_nav::hedge_pos_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp_ms: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timestamp_ms);
    s << indent << "x_m: ";
    Printer<double>::stream(s, indent + "  ", v.x_m);
    s << indent << "y_m: ";
    Printer<double>::stream(s, indent + "  ", v.y_m);
    s << indent << "z_m: ";
    Printer<double>::stream(s, indent + "  ", v.z_m);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARVELMIND_NAV_MESSAGE_HEDGE_POS_H
